general:
  auth:
          # default: test
    us-east-2: test
project:
  name: cft-test
tests:
  mytest:
    template: ./vpc.yml
    regions:
    - "us-east-2"
    parameters: 
      S3BucketName: '$[taskcat_autobucket]'
