version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo install phase started on `date`
      - python --version
      - 'curl -O https://bootstrap.pypa.io/get-pip.py'
      - python3 get-pip.py
      - pip install --upgrade pip
      - pip3 install taskcat
      - pip3 install --upgrade taskcat
  build:
    commands:
      - echo Build phase started on `date`
      # - taskcat test  run --no-delete
      # - taskcat test run -k 
      - aws --version
      - aws sts get-caller-identity
      - mkdir $HOME/.aws
      - touch $HOME/.aws/credentials
      - touch $HOME/.aws/config
      - echo -e "[test]" >> $HOME/.aws/config
      - echo -e "[test]" >> $HOME/.aws/credentials
      - echo -e "role_arn = arn:aws:iam::869862938706:role/sandbox-switch" >> $HOME/.aws/credentials
      - echo -e "credential_source = Ec2InstanceMetadata" >> $HOME/.aws/credentials 
      - taskcat test run --no-delete
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
