version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo install phase started on `date`
      - python --version
      - 'curl -O https://bootstrap.pypa.io/get-pip.py'
      - python3 get-pip.py
      - pip install --upgrade pip
      - pip3 install taskcat
      - pip3 install --upgrade taskcat
  build:
    commands:
      - echo Build phase started on `date`
      # - taskcat test  run --no-delete
      # - taskcat test run -k 
      - aws --version
      - yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - yum install jq -y
      - aws sts get-caller-identity
        #- aws sts get-caller-identity --profile test
      - mkdir $HOME/.aws
      - touch $HOME/.aws/credentials
      - touch $HOME/.aws/config
      - echo -e "[test]" >> $HOME/.aws/config
      - role_arn='arn:aws:iam::869862938706:role/sandbox-switch'
      - role_session_name='test'
      - profile_name='test' 
      - temp_role=$(aws sts assume-role --role-arn $role_arn --role-session-name $role_session_name)
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile $profile_name
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile $profile_name
      - aws configure set aws_session_token $AWS_SESSION_TOKEN --profile $profile_name
      - taskcat test run --no-delete
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
